name: unsplash
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dartz: ^0.9.1
  equatable: ^1.2.0
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  flutter_bloc: ^4.0.0
  cached_network_image: ^2.2.0+1
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
